[package]
name = "xilem_web-error-message-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
xilem_web = { git = "https://github.com/linebender/xilem.git", rev = "101fa9bb7d3413c9b824921bbe10feb577200af8" }
